In [ ]:
pip install pandas

# Pandas

Pandas ek powerful Python library hai jo:

* data ko read karne
* organize karne
* clean karne
* analyze karne
* manipulate karne

ke liye use hoti hai.

Ye specially Data Science, Machine Learning, aur Data Analysis me use hoti hai.
Pandas me table ko DataFrame bolte hain.

### Data Science me use

Pandas ka use:

* CSV files
* Excel files
* Data cleaning
* Data analysis

Machine Learning preprocessing me hota hai.

| Term      | Meaning              |
| --------- | -------------------- |
| Series    | Single column        |
| DataFrame | Complete table       |
| CSV       | Comma separated file |

In [1]:
import os
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv(r"C:\Users\Jaishree\Downloads\Used_Bikes.csv")

In [3]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000,Delhi,22000,First Owner,4,100,Hero
32644,TVS Apache RTR 180cc,30000,Karnal,6639,First Owner,9,180,TVS
32645,Bajaj Avenger Street 220,60000,Delhi,20373,First Owner,6,220,Bajaj
32646,Hero Super Splendor 125cc,15600,Jaipur,84186,First Owner,16,125,Hero
32647,Bajaj Pulsar 150cc,22000,Pune,60857,First Owner,13,150,Bajaj

In [4]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha

In [5]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
5,Yamaha FZs 150cc,53499,Delhi,25000,First Owner,6,150,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000,Delhi,8200,First Owner,3,160,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000,Delhi,12645,First Owner,3,100,Hero
8,Royal Enfield Thunderbird X 350cc,145000,Bangalore,9190,First Owner,3,350,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000,Delhi,19000,Second Owner,7,500,Royal Enfield

In [6]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000,Delhi,22000,First Owner,4,100,Hero
32644,TVS Apache RTR 180cc,30000,Karnal,6639,First Owner,9,180,TVS
32645,Bajaj Avenger Street 220,60000,Delhi,20373,First Owner,6,220,Bajaj
32646,Hero Super Splendor 125cc,15600,Jaipur,84186,First Owner,16,125,Hero
32647,Bajaj Pulsar 150cc,22000,Pune,60857,First Owner,13,150,Bajaj

In [7]:
df.tail(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
32633,Royal Enfield Classic 350cc,87000,Gautam Buddha Nagar,16336,First Owner,7,350,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000,Mumbai,13858,Second Owner,11,350,Royal Enfield
32635,Suzuki Zeus 125cc,35000,Ahmedabad,11885,First Owner,12,125,Suzuki
32636,KTM RC 390cc,196700,Mumbai,13216,First Owner,4,390,KTM
32637,Bajaj Pulsar 150cc,25000,Delhi,32588,First Owner,9,150,Bajaj
32638,Yamaha Fazer 25 250cc,123000,Kadapa,14500,First Owner,4,250,Yamaha
32639,Royal Enfield Classic 350cc,95500,Delhi,18000,First Owner,8,350,Royal Enfield
32640,Hero Passion Pro 100cc,32000,Delhi,12000,First Owner,6,100,Hero
32641,Bajaj Avenger 220cc,41000,Delhi,20245,Second Owner,11,220,Bajaj
32642,Hero Passion 100cc,15000,Perumbavoor,35000,Second Owner,19,100,Hero
32643,Hero Passion Pro 100cc,39000,Delhi,22000,First Owner,4,100,Hero
32644,TVS Apache RTR 180cc,30000,Karnal,6639,First Owner,9,180,TVS
32645,Bajaj Avenger Street 220,60000,Delhi,20373,First Owner,6,220,Bajaj
32646,Hero Super Splendor 125cc,15600,Jaipur,84186,First Owner,16,125,Hero
32647,Bajaj Pulsar 150cc,22000,Pune,60857,First Owner,13,150,Bajaj

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  int64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  int64
 4   owner       32648 non-null  str
 5   age         32648 non-null  int64
 6   power       32648 non-null  int64
 7   brand       32648 non-null  str
dtypes: int64(4), str(4)
memory usage: 2.0 MB

In [ ]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [ ]:
df['age']

0         3
1         4
2         8
3         4
4         3
         ..
32643     4
32644     9
32645     6
32646    16
32647    13
Name: age, Length: 32648, dtype: int64

In [ ]:
df['brand']

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [8]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [ ]:
df[['brand','age']]

               brand  age
0                TVS    3
1      Royal Enfield    4
2            Triumph    8
3                TVS    4
4             Yamaha    3
...              ...  ...
32643           Hero    4
32644            TVS    9
32645          Bajaj    6
32646           Hero   16
32647          Bajaj   13

[32648 rows x 2 columns]

In [ ]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [ ]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [ ]:
df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [ ]:
df['brand'].nunique()

23

In [ ]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [9]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [10]:
df.duplicated().sum()

np.int64(25324)

In [11]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero
9369,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj
9370,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj
9372,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj

In [12]:
df.duplicated().sum()

np.int64(25324)

In [3]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:

df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [18]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   int64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   int64
 4   owner       7324 non-null   str
 5   age         7324 non-null   int64
 6   power       7324 non-null   int64
 7   brand       7324 non-null   str
dtypes: int64(4), str(4)
memory usage: 515.0 KB

In [20]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [21]:
owner_dict={0:'First Owner',1:'Second Owner',2:'Third Owner',3:'Fourth & Above Owner',4:'Test Drive Car'}

In [9]:
df

NameError: name 'df' is not defined

In [23]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   int64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   int64
 4   owner       7324 non-null   str
 5   age         7324 non-null   int64
 6   power       7324 non-null   int64
 7   brand       7324 non-null   str
dtypes: int64(4), str(4)
memory usage: 515.0 KB

In [25]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero
9369,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj
9370,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj
9372,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj

In [26]:
brand_dict = {
     'TVS':1, 'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [27]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero
9369,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj
9370,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj
9372,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   int64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   int64
 4   owner       7324 non-null   str
 5   age         7324 non-null   int64
 6   power       7324 non-null   int64
 7   brand       7324 non-null   str
dtypes: int64(4), str(4)
memory usage: 515.0 KB

In [29]:
obj_val =df.select_dtypes(include='O')

C:\Users\Jaishree\AppData\Local\Temp\ipykernel_3932\2170337667.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val =df.select_dtypes(include='O')

In [30]:
obj_val

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [31]:
num_val =df.select_dtypes(exclude='O')

In [32]:
num_val

       price  kms_driven  age  power
0      35000       17654    3    110
1     119900       11000    4    350
2     600000         110    8    675
3      65000       16329    4    180
4      80000       10000    3    150
...      ...         ...  ...    ...
9362   25000       48587    8    150
9369   35000       60000    9    220
9370  450000        3430    4    750
9371  139000       21300    4    400
9372   80000        7127    5    220

[7324 rows x 4 columns]

In [33]:
complete_Data =pd.concat([obj_val, num_val], axis=1)

In [34]:
complete_Data

,bike_name,city,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS,35000,17654,3,110
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield,119900,11000,4,350
2,Triumph Daytona 675R,Delhi,First Owner,Triumph,600000,110,8,675
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS,65000,16329,4,180
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha,80000,10000,3,150
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero,25000,48587,8,150
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj,35000,60000,9,220
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson,450000,3430,4,750
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj,139000,21300,4,400
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj,80000,7127,5,220

In [35]:
tvs_brand =df[df['brand']=='TVS']

In [36]:
tvs_brand['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner']
Length: 3, dtype: str

In [37]:
# brand = " royal", km = >50Km, owner = 1st, age 2 sal se km

In [38]:
tvs_first =tvs_brand[tvs_brand['owner']=='First Owner']

In [39]:
tvs_first[tvs_first['age']<=2]

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000,Hyderabad,16000,First Owner,2,160,TVS
360,TVS Apache RTR 160 4V Disc,78700,Rudrapur,3710,First Owner,2,160,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500,Delhi,10000,First Owner,2,200,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000,Delhi,7000,First Owner,2,160,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000,Gurgaon,7000,First Owner,2,160,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800,Delhi,1050,First Owner,2,160,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000,Delhi,3000,First Owner,2,160,TVS
757,TVS Apache RTR 160 4V Disc,74700,Gautam Buddha Nagar,20194,First Owner,2,160,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500,Bangalore,2500,First Owner,2,200,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000,Bangalore,1300,First Owner,1,200,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000,Jaipur,749,First Owner,1,160,TVS
1171,TVS Apache RR310,200000,Mumbai,4400,First Owner,2,310,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000,Hyderabad,530,First Owner,2,200,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000,Delhi,8000,First Owner,2,160,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000,Chennai,3100,First Owner,2,200,TVS
1712,TVS Apache RR310 Slipper Clutch,224000,Vadodara,3900,First Owner,2,310,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500,Delhi,2800,First Owner,2,200,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135,Delhi,2800,First Owner,2,160,TVS
1802,TVS Apache RTR 180cc,88000,Gurgaon,900,First Owner,2,180,TVS
2325,TVS Apache RTR 200 4V ABS,92000,Mumbai,4500,First Owner,2,200,TVS
2360,TVS Victor 110cc Disc SBT,54000,Delhi,6000,First Owner,2,110,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000,Delhi,11496,First Owner,2,160,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000,Ahmedabad,893,First Owner,2,160,TVS
3178,TVS Apache RTR 160cc White Race Edition Rear Disc,82000,Bangalore,52198,First Owner,2,160,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000,Mumbai,6821,First Owner,2,160,TVS
3440,TVS Apache RTR 160 4V Disc,92000,Mumbai,14289,First Owner,2,160,TVS
4251,TVS Star City Plus 110cc,51000,Ahmedabad,12000,First Owner,2,110,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000,Ghaziabad,2672,First Owner,2,160,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000,Delhi,1890,First Owner,2,200,TVS
5510,TVS Apache RTR 180cc,90000,Ghaziabad,3095,First Owner,2,180,TVS
5557,TVS Apache RTR 200 4V FI,102000,Thane,8120,First Owner,2,200,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000,Bangalore,4000,First Owner,2,200,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700,Delhi,900,First Owner,2,160,TVS
6058,TVS Apache RR310,220000,Noida,5432,First Owner,2,310,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000,Faridabad,15228,First Owner,2,160,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000,Mumbai,7157,First Owner,2,200,TVS
7055,TVS Sport 100cc,46000,Faridabad,6222,First Owner,2,100,TVS
7311,TVS Apache RTR 180cc,70000,Jaipur,207102,First Owner,2,180,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000,Mumbai,4442,First Owner,2,200,TVS
9322,TVS Radeon 110cc Drum SBT,58000,Delhi,4020,First Owner,2,110,TVS

In [40]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000,Ahmedabad,17654,First Owner,3,110,TVS
1,Royal Enfield Classic 350cc,119900,Delhi,11000,First Owner,4,350,Royal Enfield
2,Triumph Daytona 675R,600000,Delhi,110,First Owner,8,675,Triumph
3,TVS Apache RTR 180cc,65000,Bangalore,16329,First Owner,4,180,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000,Bangalore,10000,First Owner,3,150,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000,Delhi,48587,First Owner,8,150,Hero
9369,Bajaj Avenger 220cc,35000,Bangalore,60000,First Owner,9,220,Bajaj
9370,Harley-Davidson Street 750 ABS,450000,Jodhpur,3430,First Owner,4,750,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000,Hyderabad,21300,First Owner,4,400,Bajaj
9372,Bajaj Avenger Street 220,80000,Hyderabad,7127,First Owner,5,220,Bajaj

In [41]:
tvvs_brand=df[df['brand']=='TVS']

In [42]:
tvs_under2 =tvs_brand[tvvs_brand['age']<=2]

In [ ]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) ]

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500,Samastipur,4550,First Owner,2,500,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000,Navi Mumbai,3800,First Owner,2,650,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300,Vadodara,14000,First Owner,2,410,Royal Enfield
194,Royal Enfield Electra 350cc,145000,Bangalore,4000,First Owner,2,350,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982,Hamirpur(hp),7000,First Owner,2,410,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500,Mumbai,1608,First Owner,2,350,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000,Delhi,417,First Owner,2,500,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000,Bangalore,4411,First Owner,2,350,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000,Ghaziabad,12400,First Owner,2,350,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200,Mumbai,1000,First Owner,2,350,Royal Enfield

In [44]:
tvs_under2[tvs_under2['kms_driven']<=20000]

,bike_name,price,city,kms_driven,owner,age,power,brand
193,TVS Apache RTR 160 4V DISC ABS BS6,85000,Hyderabad,16000,First Owner,2,160,TVS
360,TVS Apache RTR 160 4V Disc,78700,Rudrapur,3710,First Owner,2,160,TVS
401,TVS Apache RTR 200 4V ABS Race Edition,108500,Delhi,10000,First Owner,2,200,TVS
425,TVS Apache RTR 160 4V DISC ABS,87000,Delhi,7000,First Owner,2,160,TVS
511,TVS Apache RTR 160 4V DRUM ABS,85000,Gurgaon,7000,First Owner,2,160,TVS
594,TVS Apache RTR 160 4V DISC ABS,91800,Delhi,1050,First Owner,2,160,TVS
664,TVS Apache RTR 160 4V DISC ABS,89000,Delhi,3000,First Owner,2,160,TVS
1097,TVS Apache RTR 200 4V Carburetor Race Edition 2.0,93500,Bangalore,2500,First Owner,2,200,TVS
1126,TVS Apache RTR 200 4V Dual Channel ABS BS6,130000,Bangalore,1300,First Owner,1,200,TVS
1132,TVS Apache RTR 160 4V DISC ABS BS6,98000,Jaipur,749,First Owner,1,160,TVS
1171,TVS Apache RR310,200000,Mumbai,4400,First Owner,2,310,TVS
1318,TVS Apache RTR 200 4V ABS Race Edition,125000,Hyderabad,530,First Owner,2,200,TVS
1514,TVS Apache RTR 160cc Matt Red Rear Disc,76000,Delhi,8000,First Owner,2,160,TVS
1678,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,122000,Chennai,3100,First Owner,2,200,TVS
1712,TVS Apache RR310 Slipper Clutch,224000,Vadodara,3900,First Owner,2,310,TVS
1741,TVS Apache RTR 200 4V Carburetor Pirelli Tyres...,98500,Delhi,2800,First Owner,2,200,TVS
1762,TVS Apache RTR 160 4V DISC ABS,89135,Delhi,2800,First Owner,2,160,TVS
1802,TVS Apache RTR 180cc,88000,Gurgaon,900,First Owner,2,180,TVS
2325,TVS Apache RTR 200 4V ABS,92000,Mumbai,4500,First Owner,2,200,TVS
2360,TVS Victor 110cc Disc SBT,54000,Delhi,6000,First Owner,2,110,TVS
2415,TVS Apache RTR 160 4V DISC ABS,85000,Delhi,11496,First Owner,2,160,TVS
3071,TVS Apache RTR 160 4V DISC ABS,94000,Ahmedabad,893,First Owner,2,160,TVS
3333,TVS Apache RTR 160 4V Carburetor With Rear Disc,85000,Mumbai,6821,First Owner,2,160,TVS
3440,TVS Apache RTR 160 4V Disc,92000,Mumbai,14289,First Owner,2,160,TVS
4251,TVS Star City Plus 110cc,51000,Ahmedabad,12000,First Owner,2,110,TVS
4367,TVS Apache RTR 160 4V Carburetor,90000,Ghaziabad,2672,First Owner,2,160,TVS
5506,TVS Apache RTR 200 4V ABS Race Edition,106000,Delhi,1890,First Owner,2,200,TVS
5510,TVS Apache RTR 180cc,90000,Ghaziabad,3095,First Owner,2,180,TVS
5557,TVS Apache RTR 200 4V FI,102000,Thane,8120,First Owner,2,200,TVS
5805,TVS Apache RTR 200 4V ABS Race Edition,128000,Bangalore,4000,First Owner,2,200,TVS
6003,TVS Apache RTR 160 4V Carburetor,90700,Delhi,900,First Owner,2,160,TVS
6058,TVS Apache RR310,220000,Noida,5432,First Owner,2,310,TVS
6571,TVS Apache RTR 160 4V Carburetor,86000,Faridabad,15228,First Owner,2,160,TVS
6787,TVS Apache RTR 200 4V Race Edition 2.0,106000,Mumbai,7157,First Owner,2,200,TVS
7055,TVS Sport 100cc,46000,Faridabad,6222,First Owner,2,100,TVS
8883,TVS Apache RTR 200 4V ABS Race Edition,120000,Mumbai,4442,First Owner,2,200,TVS
9322,TVS Radeon 110cc Drum SBT,58000,Delhi,4020,First Owner,2,110,TVS

In [45]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [46]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [47]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [48]:
# df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<150000) ]
df.query("brand=='Royal Enfield' and age <=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500,Samastipur,4550,First Owner,2,500,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000,Navi Mumbai,3800,First Owner,2,650,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300,Vadodara,14000,First Owner,2,410,Royal Enfield
194,Royal Enfield Electra 350cc,145000,Bangalore,4000,First Owner,2,350,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982,Hamirpur(hp),7000,First Owner,2,410,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500,Mumbai,1608,First Owner,2,350,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000,Delhi,417,First Owner,2,500,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000,Bangalore,4411,First Owner,2,350,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000,Ghaziabad,12400,First Owner,2,350,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200,Mumbai,1000,First Owner,2,350,Royal Enfield

In [49]:
df.drop(['bike_name', 'city'], axis=1, inplace=True)

In [50]:
df.duplicated().sum()

np.int64(18)

In [51]:
df.drop_duplicates(inplace=True)

In [53]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [54]:
x =df.drop('price', axis=1)

In [55]:
y =df[['price']]

In [56]:
y

       price
0      35000
1     119900
2     600000
3      65000
4      80000
...      ...
9362   25000
9369   35000
9370  450000
9371  139000
9372   80000

[7306 rows x 1 columns]

In [57]:
x

      kms_driven        owner  age  power            brand
0          17654  First Owner    3    110              TVS
1          11000  First Owner    4    350    Royal Enfield
2            110  First Owner    8    675          Triumph
3          16329  First Owner    4    180              TVS
4          10000  First Owner    3    150           Yamaha
...          ...          ...  ...    ...              ...
9362       48587  First Owner    8    150             Hero
9369       60000  First Owner    9    220            Bajaj
9370        3430  First Owner    4    750  Harley-Davidson
9371       21300  First Owner    4    400            Bajaj
9372        7127  First Owner    5    220            Bajaj

[7306 rows x 5 columns]

In [58]:
df

       price  kms_driven        owner  age  power            brand
0      35000       17654  First Owner    3    110              TVS
1     119900       11000  First Owner    4    350    Royal Enfield
2     600000         110  First Owner    8    675          Triumph
3      65000       16329  First Owner    4    180              TVS
4      80000       10000  First Owner    3    150           Yamaha
...      ...         ...          ...  ...    ...              ...
9362   25000       48587  First Owner    8    150             Hero
9369   35000       60000  First Owner    9    220            Bajaj
9370  450000        3430  First Owner    4    750  Harley-Davidson
9371  139000       21300  First Owner    4    400            Bajaj
9372   80000        7127  First Owner    5    220            Bajaj

[7306 rows x 6 columns]

In [59]:
df.to_csv("clean_bike_data.csv")

In [60]:
df

       price  kms_driven        owner  age  power            brand
0      35000       17654  First Owner    3    110              TVS
1     119900       11000  First Owner    4    350    Royal Enfield
2     600000         110  First Owner    8    675          Triumph
3      65000       16329  First Owner    4    180              TVS
4      80000       10000  First Owner    3    150           Yamaha
...      ...         ...          ...  ...    ...              ...
9362   25000       48587  First Owner    8    150             Hero
9369   35000       60000  First Owner    9    220            Bajaj
9370  450000        3430  First Owner    4    750  Harley-Davidson
9371  139000       21300  First Owner    4    400            Bajaj
9372   80000        7127  First Owner    5    220            Bajaj

[7306 rows x 6 columns]